wandb:
  run_name: "1b_70b_simpl"

model:
  name: "microsoft/deberta-v3-small"
  dropout: 0.2
  hidden_size: 384

data:
  input: "data/1b_70b_wins_simpl.jsonl"
  val_size: 100
  augment: true
  aug_factor: 3

training:
  batch_size: 32
  epochs: 10
  lr: 0.0003
  clip_grad_norm: 1.0

checkpoint: "checkpoints"
