wandb:
  run_name: "1b_8b_base_t=0"

model:
  name: "microsoft/deberta-v2-xlarge"
  dropout: 0.1
  hidden_size: 768

data:
  input: "outputs/1b_8b_wins.jsonl"
  val_size: 50

training:
  batch_size: 32
  epochs: 100
  lr: 0.01
  clip_grad_norm: 1.0

checkpoint: "checkpoints"
