wandb:
  run_name: "8b_70b"

model:
  name: "microsoft/deberta-v3-small"
  dropout: 0.2
  hidden_size: 384

data:
  input: "outputs/1b_8b_wins.jsonl"
  val_size: 50
  augment: false

training:
  batch_size: 32
  epochs: 10
  lr: 0.0003
  clip_grad_norm: 1.0

checkpoint: "checkpoints"
